Modify test to remove calls to old interface
compiler-research/cppyy pull request #32
Opened 2023-04-21 11:14 UTC by sudo-panda

This test, `test04_naming_of_ostringstream`, was used to compare the output of ShortType and GetClass for different strings that refer to the same class. As we no longer use these interfaces, one way to test these can be though the proxies created by cppyy.

RFC: @wlav

2023-04-21 17:28 UTC, wlav requested changes
Nit: don't explain the history of the changed code in the comments, but just explain what it does: ensure that template lookups with and without default parameters result in the exact same proxy.

2023-04-28 17:43 UTC, vgvassilev commented
ping.

2023-05-08 12:41 UTC, vgvassilev commented
@sudo-panda, can you rebase and address the comment?

2023-05-16 17:41 UTC, merged

2023-05-16 18:42 UTC, vgvassilev commented
@sudo-panda, we should probably reopen the PR and investigate why this failed.